const general_list =
[
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "A López, Citigroup no lo contrataría ni para limpiar las ventanas. Con una disculpa al muy digno trabajo de limpiar ventanas.",
    "author": "Sergio Negrete Cárdenas",
    "info_author": "",
    "comment": "Dando y dando: yo me disculpo para simular que entiendo por qué debería disculparme, y ustedes se disculpan por tener esos trabajos que la verdad sí son materia para comparaciones peyorativas."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Macron es un miserable, digno heredero de Robespierre, Saint-Just y demás cabecillas del Terror desencadenado por la Revolución Francesa. Ahora defiende esa variante de los antiguos sacrificios humanos que es el derecho al aborto libre.",
    "author": "Frnando Sánchez Dragó, escritor.",
    "info_author": "",
    "comment": "1) Los jacobinos llegan a enterarse de que los anda emparentando con Macron y de inmediato mandan guillotinar al declarante. 2) Occidente debería aprender de los talibanes en materia de respeto a la vida y derechos humanos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Compré mi boleto en clase Turista en el avión. Pero me percibo como pasajero de Primera Clase. Ahora le voy a decir a la aeromoza que me cambie de lugar adelante, y si me dice que no, que estoy loco, la voy a acusar de Discurso de Odio.",
    "author": "Luis Pazos P., acerca de la transexualidad.",
    "info_author": "",
    "comment": "Eso: ser transexual es pasarse de listo para adquirir boletos con descuento. Ahora bien, no habría que menospreciar el poder de la percepción: usted percibe que sus metáforas son geniales y henos aquí."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "La buena noticia para AMLO es que habrá muchos más pobres dispuestos a venderle su voto por migajas.",
    "author": "Jorge Suárez Vélez",
    "info_author": "",
    "comment": "La otra buena noticia para AMLO es que el único hábito a nuestra disposición para entender su popularidad consiste en llamar migajas a las reivindicaciones sociales."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Aquí está papá.",
    "author": "Cuauhtémoc Blanco, defendiéndose de las acusaciones que lo ligan al narcotráfico.",
    "info_author": "",
    "comment": " '¿Papá' será su alias dentro del hampa?"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Claudia Sheinbaum impuso el cubrebocas. Con esto se empató con la derecha. La verdad (...) creo que ha sido uno de los errores más graves de alguien del movimiento.",
    "author": "Gerardo Fernández Noroña.",
    "info_author": "",
    "comment": "Aprendan de mí: me niego a usar el cubrebocas y sólo me ha dado covid dos veces."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Cuando tienen un problema de taponación, se meten, los meten, se meten a sus casas llenos de miedo, a tragar chatarra y media, que el propio doctor López Gatell lo ha dicho, que eso hace daño, tapona los pulmones, no pueden respirar bronquios y pulmones. Ya no saben anatomía y fisiología. Eso es elemental.",
    "author": "Participante de la manifestación antivacunas en Palacio Nacional explica (más o menos) la relación entre los bronquios y comer papitas.",
    "info_author": "",
    "comment": "Qué es la ideología de género desde el punto de vista de la Iglesia Católica? Un ministro de culto nos lo explica: La ideología de género pretende: menos personas en el mundo [¿dónde quedaron esas hembras alfa que parían ocho hijos sin andar lloriqueando por la ausencia de una carrera profesional?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2022",
    "text": "Qué es la ideología de género desde el punto de vista de la Iglesia Católica? Un ministro de culto nos lo explica:",
    "author": "La ideología de género pretende:",
    "info_author": "",
    "comment": "menos personas en el mundo [¿dónde quedaron esas hembras alfa que parían ocho hijos sin andar lloriqueando por la ausencia de una carrera profesional?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Antes los políticos eran más sinceros, no tenían un doble discurso, no se daban baños de pureza, no actuaban con doble moral, don Fidel Velázquez decía: ‘Soy charro y qué’.",
    "author": "AMLO",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Los expertos y los especialistas nos están dando cuando mucho 2.5. Yo planteo el 5. -¿En qué lo fundamenta? -Tengo información y además soy optimista.",
    "author": "AMLO, acerca de los pronósticos de crecimiento económico para México",
    "info_author": "",
    "comment": "De la pseudociencia neoliberal pasamos a la metafísica del optimismo. Ojalá el próximo gobierno acuda a la astrología para acabar de abrazar la diversidad epistémica. Por ejemplo, los despidos masivos se anunciarán con cosas tipo: 'Sector industrial: hora de cerrar ciclos y aprender a soltar'."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Yo tenía la solución a nivel de mercadotecnia. Esta campaña no se gana con publicidad, se gana con propaganda. Y mientras más mentiras des contra Morena, mejor te va.",
    "author": "Carlos Alazraki",
    "info_author": "",
    "comment": "Editorialización a cargo de Roberto Madrazo: “Genio, yo conozco a uno: es mi hermano, se llama Carlos Alazraki. Ese es un genio”.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Como bien dijo Abel Quezada, NACO no es ser pobre ni de piel oscura. Es ser vulgar, ostentoso y grosero. Nuevo rico, pues.",
    "author": "Paco Calderón",
    "info_author": "",
    "comment": "Los ricos de abolengo son decentísimos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "A la ruleta apuestan los dos: capitalista y trabajador. Si se pierde en la ruleta, el trabajador no pierde nada y el capitalista todo. Por eso le paga al capitalista para que le cubra los riesgos.",
    "author": "Juan Ramón Rallo, economista",
    "info_author": "",
    "comment": "Tuit avalado por los dos millones de trabajadores que mueren cada año en accidentes laborales. PD. ¡Con que pierden todo! Que los capitalistas no lean este tuit o se les va a ocurrir inventar las Sociedades de Responsabilidad Limitada."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "El presidente Andrés Manuel López Obrador, encarna a la Nación, a la patria y al pueblo. [...] Los que se oponen al Presidente de México [...] son ¡unos traidores a la nación, la patria y al pueblo!",
    "author": "Senadores de Morena",
    "info_author": "",
    "comment": "Lo que le faltaba a la izquierda era suscribir la teología de la encarnación. Un escándalo más y nos pronunciamos a favor de reconocer la infalibilidad de del presidente y la incuestionabilidad de los dogmas de la Santa Cuatrinidad."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Soñar es pensar a lo grande. Es apuntar a la luna sabiendo que si te quedas corto, alcanzarás las estrellas.",
    "author": "Anxo Pérez, “Los 88 peldaños del éxito”",
    "info_author": "",
    "comment": "Estamos deseosos de que el escritor publique un diagrama de su modelo astronómico. ¿A cuántos metros de altura se imagina que están las estrellas? ¿Van antes o después del Everest?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "No sólo tenemos la cárcel de DC, que es el Gulag DC, sino que ahora tenemos a la Policía Gaspacho de Nancy Pelosi.",
    "author": "Marjorie Taylor Greene, diputada estadounidense, víctima de la traicionera  cercanía fonética entre Gestapo y Gaspacho.",
    "info_author": "",
    "comment": "Traía a un amigo mío colombiano mafiosón con otra 9 milímetros más chueca que él. Roebrto Palazuelos No importa que digan que hagan, la verdad siempre sale a la luz. Solo me están haciendo más fuerte, más grande y voy en camino a cumplir con mi destino. Vamos a terminar con el poder corrupto que tanto ha dañado a 🇲🇽. Yo sí amo a mi país, a su gente y voy de la mano de Dios. Roebrto Palazuelos [De la mano de Dios y de la del amigo mafiosón armado con una pistola más chueca que él."
  }, 
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Soy plenamente feliz. La vida ha sido generosa, y ustedes conmigo.",
    "author": "Elba Esther Gordillo, tras su boda.",
    "info_author": "",
    "comment": "Por “ustedes” me refiero a los maestros. Por “vida” me refiero a sus puntuales cuotas sindicales.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "López tiene que entender: si camina como pato, si huele a pato, si tiene plumas como pato, es que es Jose Ramon.",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "Duda teológica legítima: ¿Y si en realidad Vicente Fox es Dios, y a través de Twitter revela las reglas silogísticas con las que creó el mundo? Eso explicaría tantas cosas."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2022",
    "text": "Hola Texas. Es grandioso volver a este hermoso estado con miles de patriotas estadounidenses orgullosos que creen en la familia, la libertad, Dios, el país y, por cierto, el petróleo y las armas.",
    "author": "Donald Trump",
    "info_author": "",
    "comment": "Y luego dicen que la derecha no tiene un programa ideológicamente sólido."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2022",
    "text": "En el próximo sexenio se revertirá ese decreto. El NAIM será realidad en cuanto saquemos a estos léperos del poder. El primer vuelo será a Canadá, como símbolo de la aspiración de los ciudadanos por un país seguro, con Estado de derecho, educación, salud, prosperidad y libertad.",
    "author": "Lilly Téllez, promotora del primer aeropuerto subacuático y diseñadora de rutas simbólicas.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2022",
    "text": "Debemos dejar de pensar que envejecer es un proceso común y natural. Envejecer es una enfermedad y, como tal, es algo que se puede tratar o incluso curar.",
    "author": "Martha Debayle",
    "info_author": "",
    "comment": "Alguien avísele a la experta que ya existen células que se niegan a envejecer y destruirse: las llamamos cáncer."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "El recorrido de López Obrador [...] traza muchas analogías, por cuanto a aislamiento, desconfianza y represalias contra quienes fueron leales, con Maximilien Robespierre.",
    "author": "Raymundo Riva Palacio",
    "info_author": "",
    "comment": "Amanecimos dadaístas de la glándula de las analogías. Proonemos una entre AMLO y Luis XIV, uno apodado el “Rey Sol”, otro oriundo de una tierra donde hace mucho calor. ¿Y por qué hace calor? Por el sol. ¿Y cómo le decían al Luis XIV? Rey sol. Práticamente vivimos en una monarquía absolutista."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Para un enfermo terminal con dolores ordinarios -soportables- es mejor no pedir la sedación. Así el enfermo tiene ocasión de llevar su dolor con fe y por amor a Jesús, y ganar méritos para la Vida Eterna.",
    "author": "Padre Eduardo Hayen",
    "info_author": "",
    "comment": "Qué consuelo para un moribundo imaginarse al Padre Celestial con un cronómetro en la mano contando los minutos que le va a apuntar en la boleta. Total, nunca se sabe: un día usted se pega en el dedo chiquito del pie y resulta que ese dolor es la morralla espiritual con la que acompleta para la salvación de su alma."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Esto parece dictadura. Huele a dictadura. Es yá una dictadura.",
    "author": "Vicente Fox, director del Instituto para Prevenir las Ideas y Combatir la Sintaxis",
    "info_author": "",
    "comment": "Según la RAE, el “acento emocional” se utiliza para distinguir un “ya” calmo, mesurado, de un “yá” exaltado y vehemente. Por ejemplo: “ya voy”, “yá valimos” "
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Con 1/3 de las casillas instaladas, lo lógico era esperar 1 millón de votos, una tercera parte de los 3 que tuvo en 2018...",
    "author": "Matí Batres",
    "info_author": "",
    "comment": "¡Ofertón en el bazar de la inferencia! ¡Compre la regla de tres y llévese gratis la causalidad y la correlación!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Al diputado morenista Mier le faltan dos letras al final del apellido.",
    "author": "Jorge Berry",
    "info_author": "",
    "comment": "Qué original. Cuánto ingenio. ¿Qué insultos habrá utilizado el señor cuando tenía siete años?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Las mujeres dicen buscar un Príncipe Azul, pero lo que realmente les atrae es la Bestia. El Príncipe llega a aburrirles, la Bestia siempre les es un reto",
    "author": "",
    "info_author": "",
    "comment": "Es fundamental que las mujeres lean esta clase de declaraciones para que lleguen a conocerse a sí mismas. Sabemos tanto sobre ellas…."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2022",
    "text": "Samuel admira mucho a J.F. Kennedy, ¿sientes lo mismo por Jackie? La verdad no sé nada de esa historia. Historia era la clase en la que peor me iba en el colegio. La mexicana sí, pero más tipo maya o azteca. Siento que fui maya en otra vida, porque voy a las pirámides de Chiapas y siento algo curioso. La neta, de Estados Unidos no sé. Sé que hay una película de ella y después la varé.",
    "author": "Mariana Rodríguez, primera dama de Nuevo León en esta vida",
    "info_author": "",
    "comment": "Si le faltan motivos para hacerse creyente considere que el infierno podría ser una conversación eterna entre Mariana Rodríguez y Ricardo Salinas Pliego."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "La solución para las violaciones, abusos sexuales y similares es educar a todos desde niños a ser puros hasta el matrimonio y fieles hasta la muerte.",
    "author": "Adolfo Castillón",
    "info_author": "",
    "comment": "Ahí tiene usted la edad media europea: ni una sola violación, ni un solo abuso sexual..."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "No habrá solución definitiva al aborto hasta que el divorcio quede prohibido. Es urgente defender la familia como célula básica de toda sociedad, fuera de los caprichos individualistas que nos hacen creer que tenemos libertad para hacer lo que sea sin importar las consecuencias.",
    "author": "Leonardo Brown",
    "info_author": "",
    "comment": "Que el compañero desarrolle su teoría: ¿ya consideró que, según algunos biólogos, la fecundación puede producirse incluso en ausencia de certificados de no divorcio? Por lo demás, reconozcamos que la implementación del plan tiene un problema: si se prohíbe el divorcio, ¿qué demente va a tomar el riesgo de casarse? ¿Qué va a seguir? ¿Hacer obligatorio el matrimonio, prohibir el sexo extramarital?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "Y sí. Yo volvería a utilizar toda la fuerza pública para defender a los ciudadanos.",
    "author": "Felipe Calderón",
    "info_author": "",
    "comment": "Eso es lo bonito del ser humano. Que puede aprender de sus errores. Este señor se encuentra una máquina del tiempo y viaja derechito al pasado para asegurarse de que todo pase exactamente igual, ni que hubiera muertos que lamentar."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "No es malo per se el que una empresa administre la distribución del agua, lo que sucede por lo general es que hay corrupción […] Yo he llegado a sostener que si el modelo neoliberal se aplicara sin corrupción no sería del todo malo.",
    "author": "AMLO",
    "info_author": "",
    "comment": "Qué gacho que el presidente le vuele su eslogan al PAN! Urge que empiece a funcionar la Escuela de Formación de Cuadros de Morena porque ya le tenemos listo al primer reprobado."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "Pero qué le dice a los familiares de estos niños? Son 14 menores que desaparecen al día. Dos de cada tres son niñas. - Que estamos trabajando todo el tiempo para garantizar la paz, enfrentando los intereses del antiguo régimen y enfrentando campañas de desprestigio como las que lleva a cabo, entre otros medios, el que conduce Carmen Aristegui.",
    "author": "AMLO",
    "info_author": "",
    "comment": "Gracias señor presiente por esta valiente campaña contra Carmen Aristegui, fundamental para dar con el paradero de los infantes."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "Menos libros y más España. Vox”",
    "author": "Pinta en la fachada de la Biblioteca Sant Gervasi-Joan Maragall de Barcelona.",
    "info_author": "",
    "comment": "Las anécdotas de Vox son lo que en México conocimos como chistes de gallegos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2022",
    "text": "El resultado es la ausencia de pesos y contrapesos en Rusia, y la decisión de un solo hombre de lanzar una invasión completamente injustificada y brutal contra Irak... contra Ucrania.",
    "author": "Declaración del inconsciente de George Bush.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "Un médico tiene el DEBER de decirle a sus pacientes que si eligen esto o lo otro su salud estará en riesgo. Pero un empresario NO puede decirle a sus asalariados que si gana tal o cual candidato sus empleos podrían estarlo. Tonterías que sólo se nos ocurren a los mexicanos.",
    "author": "Paco Calderón",
    "info_author": "",
    "comment": "Eso. El empresario es el médico del alma colectiva, el pediatra de un pueblo aquejado por una deficiencia de la vitamina del esfuerzo. Para que luego no anden diciendo que vivimos en tiempos postideológicos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "Diez pesos la hora, por ocho horas diarias te da ochenta pesos diarios. Ochenta pesos diarios por semana de 48 horas te da $3840.00 semanales. Por cuatro semanas (dos quincenas) al mes, obtienes $15,360.00 mensuales. No es un salario tan bajo. La pregunta es ¿haciendo qué?",
    "author": "Paco Calderón",
    "info_author": "",
    "comment": "Mira, Bartola, ahí te dejo estos diez pesos. Con que trabajes 190 días al mes sale un sueldo muy digno. Cuestión de voluntad (y de saber extender el espacio-tiempo)."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "Esto es un ataque a la democracia, ni en las peores épocas del PRI, hoy nuestro aliado, ya democratizado.",
    "author": "Santiago Creel",
    "info_author": "",
    "comment": "Es verdad que hay discursos familiares igual de poco meditados: “y fue así como esa señora metiche y rencorosa, a quien hoy me precio de llamar querida suegra…”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "La pregunta correcta no es “¿Porque Latinoamerica no aprende?”  La pregunta correcta es: “¿Que esta haciendo bien el progresismo en términos de marketing que sigue engañando a la gente?”. Tristemente, la política es Marketing señores, no resultados. Les guste o no.",
    "author": "Luis Pazos P.",
    "info_author": "",
    "comment": "Y la pregunta más correcta: ¿cómo evitar que los millones de pobres que engendra el capitalismo se presten para salir de extras de las campañas publicitarias de los izquierdistas? No damos una con la ortografía pero sí estamos para revelarle a la época la lista de sus preguntas pertinentes."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "A los 4 años no se da cuenta de que el crecimiento económico es de “-0”. Sí. Menos cero!",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "Fox debió deducir la existencia del “menos cero” tras escuchar hablar del “seropositivo”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "Desde mi punto de vista, dos condiciones sin ecuanon…",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "Le faltó el acento a “ecuanón”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2022",
    "text": "Yo les recomiendo a los que les interese el tema que lean a León Tolstoi, tiene un… Un día voy a dar a conocer una bibliografía, porque no necesariamente tiene que ser Lenin o Hitler para la formación.",
    "author": "AMLO",
    "info_author": "",
    "comment": "¿Dijo Hitler? ¿Y dijo “necesariamente”? ¿O sea que lo dejamos como lectura optativa? ¿Y para la formación de quién y en qué? ¿Ya juntamos a Lenin con Hitler?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "Algún día, una niña o un niño de Ucrania se acordará que unos representantes de México fueron a su país a decirles: estamos con ustedes. México no es indiferente frente a esta profunda injusticia. Y por eso vale la pena hacer política.",
    "author": "Juan Zavala, Secretario general de Movimiento Ciudadano",
    "info_author": "",
    "comment": "Niños de Ucrania, aquí les dejo el imborrable recuerdo de mi persona para que les dé fuerza y consuelo..."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "Cuando se olvida que el sexo es una cuestión [...] cuya finalidad principal es la procreación, vemos que hay personas que se liberan de esas cadenas que supone la familia, que supone el matrimonio, para dedicar su existencia a satisfacer sus deseos sexuales.",
    "author": "Juan García Gallardo, político de VOX",
    "info_author": "",
    "comment": "Si desea promocionar el matrimonio, ¿no se le ocurre nada mejor que la metáfora de las cadenas? Al respetable no le van a gustar los eslogans: “¡Libertinos del mundo, encadenáos!”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "No hicieron nada para evitar lo que hoy vivimos y lo que viene. Salvo un par de excepciones, son una bola de cobardes. Su avaricia, codicia (codos)y cobardía permitió y estimula que esto ocurra.",
    "author": "Felipe Calderón, en modo ex tóxico, dirigéndose a los empresarios, antes suyos, hoy de otro",
    "info_author": "",
    "comment": "Suena un tango vindicativo: 'Y al mirarla envilecida, a otros brazos entregada...' "
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "Tenemos que tomar en cuenta el que, si no hay la orden de reprimir al pueblo, repito, no hay nada que temer. Y estoy convencido de que los gobiernos civiles en el futuro van a ser gentes sensibles, que cada vez van a profesar más amor a nuestro pueblo, más amor al prójimo.",
    "author": "AMLO, sobre la integración de la Guardia Nacional a la Sedena.",
    "info_author": "",
    "comment": "Qué tranquilos nos quedamos, presidente. Las apelaciones al amor son toda la institucionalidad que necesitamos. Al ejército podemos regularlo con una colección de sus discursos más bonitos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "Pretender que cualquiera de nosotros va a estar a la altura del liderazgo, del compromiso, de la imaginación hecha política pública del Presidente, es equivocarnos, darnos contra la pared. Solitos no somos nadie. [Él] es el creador de este movimiento, es el origen y es el destino.",
    "author": "Adán Augusto",
    "info_author": "",
    "comment": "Reciba usted, señor presidente, este ramo de metáforas que no son en modo alguno fruto de nuestro amor a la cursilería, sino sobrio reconocimiento de que elogiarlo es la única vía que nos queda para alcanzar la unidad."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2022",
    "text": "Como alguien que ha ayudado a planificar golpes de Estado -no aquí, pero sí en otros lugares- se necesita mucho trabajo.",
    "author": "John Bolton, exconsejero de seguridad de Estados Unidos",
    "info_author": "",
    "comment": "Asesinos? Sí. ¿Cobardes? Siempre. Pero holgazanes, nunca."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Los derechos humanos son, precisamente, para los humanos. Los delincuentes son bestias que no merecen ninguna consideración.",
    "author": "América Rangel, diputada del Partido Acción Nacional.",
    "info_author": "",
    "comment": "Dónde vive la diputada? ¿Considera que nuestras instituciones penales no ejercen suficientemente la crueldad? ¡México, ese país agobiado por el exceso de derechos humanos y el déficit de brutalidad!"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Jesús Murillo Karam es preso político de López Obrador. Pueden citarme.",
    "author": "Fernando Belauzarán",
    "info_author": "",
    "comment": "La genuina izquierda ya se moviliza en defensa de los presos políticos. Libertad al compañero Murillo, perseguido por defender sus ideas, sobre todo su peculiar idea de lo que es la impartición de justicia. Alguien cíteme por el amor de Dios."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Esta pobre mujer no parece entender la relación entre productividad y sueldos. El tema no es cómo “presionar” para subir salarios, sino cómo ayudarles a los trabajadores a aumentar su productividad con mejor capacitación y acceso a mejores bienes de capital y tecnología de punta.",
    "author": "Monseñor Jorge Suárez-Velez, obispo de la Iglesia de la Utilidad Marginal, en condecendiente explicación a la economista Viri Ríos.",
    "info_author": "",
    "comment": "Aprendan de los capitalistas, que no se andan organizando para incrementar sus ganancias sino que se limitan a aceptar lo que el sapiente mercado les manda. ¿O acaso alguien se atreverá a dudar de la vigencia del modelito ese que estudié en el primer semestre de Economía?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Rindiendo homenaje al gran Porfirio Díaz, cementerio Montparnasse, Paris. En 2024 lo repatriaremos...",
    "author": "Gabriel Quadri",
    "info_author": "",
    "comment": "Y ya repatriado lo vamos a enterrar. En Cananea, por supuesto. Y luego vamos a exhumar a Juárez y mandarlo a Francia a manera de disculpa y para infundir confianza en el capital internacional. Quadri siempre atento a las palpitaiciones de la nación. Porfirio, aguanta, tu burguesía se levanta."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Enseñaremos la verdad en nuestros colegios. No dejaremos que ellos impongan su agenda ideológica. Enseñaremos que nuestros derechos provienen de Dios, no del gobierno.",
    "author": "Ron DeSantis, gobernador de Florida",
    "info_author": "",
    "comment": "¡Basta de ideologías! ¡Suscribamos las verdades autoevidentes de la religión!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Cómo ven?, va la gente… piden tele, estéreo, celulares y se les olvida que tienen que darle de comer a sus hijos, luego resulta que los malos somos los que confiamos en ellos y les damos crédito, CONSTE QUE NO LOS OBLIGAMOS a comprar…",
    "author": "Ricardo Salinas Pliego",
    "info_author": "",
    "comment": "Ni los grupos de la mafia podrían elaborar una defensa tan elocuente de la usura."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2022",
    "text": "Avanzamos sobre todo en la idea del derecho a la salud, en el cual los y las medicamentos son fundamentales para poder garantizar el acceso a la salud",
    "author": "Cristobal Cuadrado, Subsecretario de Salud de Chile",
    "info_author": "",
    "comment": "Debió haber dicho medicamentos y medicamentas, el muy excluyente."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Me huele a montaje. Cristina ya sabe que una muerte repentina, o algo trágico, puede darle puntos políticos.",
    "author": "Irving Gatell, sobre el atentado fallido contra Cristina Fernández.",
    "info_author": "",
    "comment": "La muy astuta ya se veía en la comodidad de la tumba disfrutando de todos esos puntos políticos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Si aplicamos la lógica de estos subnormales, Hitler no era racista.",
    "author": "Chumel Torres",
    "info_author": "",
    "comment": "Contexto: 1) Alguien afirma que el racismo inverso no existe. 2) Nuestro colaborador responde que si se sigue esa lógica debe concluirse que Hitler no era racista. Directo al Museo de los Silogismos Disidentes. Si un judío iba por ahí discriminando a los arios damos por demostrada la existencia del antisemitismo inverso."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Mira, yo como tengo un método… A mí cuando me dicen “Jalife le atinó”, no es cierto. Yo traigo método [...] Te vas y lo aplicas y te da resultados. Aunque tu corazoncito esté con las ucranianas que son de las mujeres más bellas del mundo, o las rusas, que no se quedan atrás, porque es la misma raza…. Entonces, el método dialéctico, pues es la tesis y la antítesis y tu sacas tu conclusión.",
    "author": "Alfredo Jalife, el analista 777.",
    "info_author": "",
    "comment": "Raza, género, dialéctica… Llévese todo al precio de una sola de mis adivinaciones retroactivas. (Notifíquese a los colegios de filosofía: la dialéctica es algo así como la regla de tres)."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Interesante cómo los activismos blancos van desnaturalizando y prostituyendo movimientos locales como el de las madres buscadoras. Ahora realizan acciones americanizadas en la estela de luz. Es muy grave la manipulación que hacen.",
    "author": "Pablo Hernández",
    "info_author": "",
    "comment": "¡No a la desmexicanización de la búsqueda de desaparecidos! Que las madres mantengan la protesta dentro de los cánones nacionales y ya no se dejen distraer de su genuina tarea que es cavar."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Yo no se ustedes pero para mi no deberían hacer simulacros, atraen la energía! Somos energía! El estar pensando y haciendo simulacros se jala esa energía!",
    "author": "José Ron, actor",
    "info_author": "",
    "comment": "También dejemos de construir edificios bajo los supuestos de que vivimos en una zona sísmica. Y clausuremos los observatorios meteorológicos porque su afán predictivo está atrayendo muchos huracanes. Se avecina una época de oro para la protección civil. ¡Prevenir es lamentar!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2022",
    "text": "Dejé de ser vegano porque me mordió un perro, entonces me enojé. [...] Estoy militando para los animales y viene uno de ellos y me muerde. [...] Me fui a McDonald's. Automáticamente.",
    "author": "Mariano de la Canal",
    "info_author": "",
    "comment": "Perro muerde a humano, luego humano come vaca."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "Marx se quedó atorado en una visión fetichista de la riqueza. Es decir, la creencia de que la riqueza tiene un valor propio. Por eso su teoría del valor-trabajo, y por eso su convicción de que hay que \"redistribuir la riqueza\". Ideas neolíticas, literalmente.",
    "author": "Irving Gatell",
    "info_author": "",
    "comment": "Todos saben que “La riqueza tiene valor propio” es prácticamente el subtítulo de El Capital. Y ni vengan los fetichistas de la argumentación a solicitar referencias sobre las concepciones de la riqueza en el neolíltico. Nuestro colaborador no habría escrito “literalmente” si no fuera con conocimiento de causa."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "Aquí hay que insistir, no hay que darse por derrotado. Yo soy de los del Coyote y el Correcaminos.",
    "author": "Germán Martínez",
    "info_author": "",
    "comment": "Compañero, si el Coyote es emblema de lo que le espera a los militantes de su causa, declinamos respetuosamente la invitación. ¿Tan vacía está ya nuestra vitrina de ídolos? ¿Pasamos de “Hasta la victoria siempre” a frases motivacionales patrocinadas por la marca Acme?",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "Felices fiestas patrias PRIMORes.",
    "author": "Yedickol Polevnsky",
    "info_author": "",
    "comment": "Pero qué sólidos andamos de los PRIncipios."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "Nuestro gobierno condena los recientes disturbios en Irán, perpetrados por los sionistas británicos y estadounidenses, y estamos seguros de que todos los problemas se resolverán con la solidaridad, el conocimiento y la comprensión del querido líder de Irán.",
    "author": "Romina Pérez, embajadora de Bolivia en Irán.",
    "info_author": "",
    "comment": "Qué casualidad que a las mujeres se les ocurre protestar justo ahora… y por “justo ahora” nos referimos al parpadeo de 43 años de tiene la república islámica. Es peligroso que las mujeres quieran anteponer sus intereses a las consideraciones geopolíticas. Si a las mujeres les hiciera bien tener más derechos, ¿no creen que el querido líder ya se los hubiera concedido?"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "La ciencia decía que el hombre provenía de los simios. [...] Si eso es cierto, ¿por qué sigue habiendo simios? Piense en ello.",
    "author": "Herschel Walker, político estadounidense, el Waterloo de Charles Darwin",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "10/2022",
    "text": "No se militariza al país -y por esto es que yo sí cambié de opinión- cuando se pone al ejército al servicio del pueblo.",
    "author": "Epigmenio Ibarra",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "El voto de las mujeres fue lo peor que le pasó a Estados Unidos. Las mujeres votan mayoritariamente basándose en sus emociones. Y los liberales son muy buenos apelando a las emociones. [...] Antes las mujeres no votaban porque su marido tomaba la decisión por ellas. [...] Si sólo votaran nuestros maridos y los propietarios, estaríamos en un lugar mucho mejor que ahora. Nosotras [...] no tendríamos tanta autoridad y poder sobre quién llega a los cargos, porque no lo merecemos\".",
    "author": "Lauren Witzke, candidata republicana al Senado en 2020.",
    "info_author": "",
    "comment": "Qué astuta. Para demostrar que las mujeres no tendrían por qué opinar, la compañera se compromete a seguir opinando. Va a convencernos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "Vamos a pedir que todos los que vendan drogas, quienes sean sorprendidos vendiendo drogas, reciban la pena de muerte por sus actos atroces.",
    "author": "Donald Trump",
    "info_author": "",
    "comment": "Es inhumano que Estados Unidos sea el país con más presos en el mundo: hay que matarlos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "Los Padres Fundadores no querían que votaran los malditos estúpidos que no han hecho una mierda en su vida. Todo este movimiento que la izquierda utiliza, ya sabes: \"salgan a votar\" [...] ¡No, maldito idiota! ¡No votes! Eres un estúpido. Eres un pedazo de escoria degenerada. En efecto, Dios te ama, pero la mayoría de nosotros no. No, no deberías votar.",
    "author": "Elijah Schaffer, conductor estadounidense, en reacción a la derrota del candidato republicano a la gubernatura de Arizona.",
    "info_author": "",
    "comment": "Le reconocemos a los insultados su derecho inalienable al amor de Dios para demostrar que somos buenos cristianos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "Y hay una religión de demonios que ama el aborto. Esa religión proaborto se manifestó. Fue más grande de lo que todos previmos, por la pasión que esos poderes demoníacos crean en su iglesia de paganos que aman matar bebés - por eso no hubo una marea roja.",
    "author": "Shane Vaughn, predicador estadounidense, explica el mal resultado de los republicanos en las elecciones intermedias.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "He pasado décadas sin una guerra. El primer presidente que hace eso en un período tan largo.",
    "author": "Donald Trump",
    "info_author": "",
    "comment": "Lo que pasa es que hay décadas de años, décadas de meses, décadas de semanas…."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "Aquí decían de Segalmex y de las tortillas y no se qué. Pues yo les diría, pues váyase a vender tortillas, que es una noble labor. Es una noble labor que ustedes se quejan tanto del incremento y no se qué tanto, cuando ustedes pus deíquense a eso, a vender tortillas y a entrar al mercado a hacer negocio de las tortillas, que tanto les gustan los jugosos negocios.",
    "author": "Otoniel García Montiel, diputado.",
    "info_author": "",
    "comment": "Nos reservamos el comentario hasta que descifremos qué quiso decir."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "11/2022",
    "text": "Lo que yo veo para todos ustedes es un México boyante...",
    "author": "Carlos Slim",
    "info_author": "",
    "comment": "Pinche ingeniero, ya ni la burla perdona."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "Yo amo a todos. Cada ser humano aporta algo valioso, especialmente Hitler. [Los nazis] también hicieron cosas buenas. Debemos dejar de despreciar a los nazis todo el tiempo.",
    "author": "Kanye West, rapero estadounidense",
    "info_author": "",
    "comment": "Los “ni antisemita ni antinazi” se solidarizan con los “ni machista ni feminista”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "A la mujer promiscua se le dice puta. Al hombre promiscuo se le aplaude. Eso NO es machismo. Para que un hombre sea promiscuo necesita tener buen cuerpo, estatus o dinero. Y para eso se necesita trabajo duro, disciplina y constancia. Meritocracia pura.",
    "author": "Christian Camacho",
    "info_author": "",
    "comment": "Claro que se le dice puta. ¿Pues qué se cree? ¿Por qué desea? ¿Por qué disfruta? Y no es machismo: es verbalizar la angustia que nos causan los cuerpos. Una cosa es que nos gusten las mujeres y otra muy diferente es que nos guste la posibilidad de que obtengan algo de placer de estar con un hombre bajo los términos que ellas deseen. Faltaba más, bola de putas. (PD. Qué ayudadota para el gremio de los padres que se desaparecen: el regadero de hijos va a cuenta de la gallardía de hombres fornidos, poderosos y constantes…)",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "Por que un “periodista” tiene que andar en “carro blindado” y con un séquito de guaruras ? Pues que tanto debe o a que mafia criminal pertenece?",
    "author": "Alfredo Jalife, sobre el atentado contra Ciro Gómez-Leyva (se respeta la ortografía del original).",
    "info_author": "",
    "comment": "El uso del blindaje nos hace sospechar que el periodista está metido en algo turbio. La otra posibilidad es que no usara blindaje y lo mataran, en cuyo caso el homicidio nos haría sospechar que el periodista andaba metido en algo turbio.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "Ser de izquierda y amante del fútbol al mismo tiempo es una hipocresía. Por un lado aseguras que la meritocracia no existe. Y por el otro admiras a futbolistas que crecieron en la pobreza pero que gracias a su talento, constancia y disciplina hoy son famosos y millonarios.",
    "author": "Christian Camacho",
    "info_author": "",
    "comment": "Si eliminamos la distinción entre posibilidad y probabilidad, demostramos facilito que vivimos en una meritocracia. Una persona cae de un cuarto piso y sale ilesa. Ergo, aventarse de cuartos pisos es una actividad segura."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "[Declaración del 20 de junio de 2019] El piso de la selección argentina será logrado en agosto de 2024. Faltan aún 5 años de decadencia. Argentina patinará gravemente en el Mundial 2022, pero ganaremos el 2026 aunque hoy no se ve a cómo. La subida desde agosto de 2024 será vertical, y sin Messi ya. El mundo delirará.",
    "author": "Carlos Maslatón, político y analista argentino",
    "info_author": "",
    "comment": "El compañero también ofrece pronósticos financieros y consejos de inversión. No dude en poner su dinero donde él le diga."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "La única hipótesis que se debe descartar es que el gobierno que yo represento no es un gobierno represor.",
    "author": "AMLO",
    "info_author": "",
    "comment": "Oh las traiciones de la doble negación!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "AURRERA ARGENTINA!!",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "La alegre deshibinición con que Fox se maneja en el mundo es un punto a favor del consumo de marihuana."
  },
    {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "12/2022",
    "text": "Yo no necesito disculpas de España por haber creado mi país, ni por habernos engendrado a los mexicanos. [...] Hay una diferencia abismal. Holanda no creó una nación en el Congo, sólo lo expolió.",
    "author": "Paco Calderón",
    "info_author": "",
    "comment": "Siguiendo con la lección de historia, Bélgica sí le debe a México una disculpa porque #NoEraPenal."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Lamento informarles que una fuente militar me confirmó que \"los verdes\" no tienen certeza de que el Ovidio detenido sea el Ovidio real! Lo lamento! Así la farsa de López Obrador!",
    "author": "Ricardo Alemán",
    "info_author": "",
    "comment": "Qué fácil no tener ninguna credibilidad que cuidar. Así cualquiera es metralleta de primicias.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Las mineras canadienses son las que más nos ayudan a proteger el territorio.",
    "author": "AMLO",
    "info_author": "",
    "comment": "Las mineras protegen el territorio de los malditos ecologistas que callaron como momias mientras los neoliberales le entregaban la nación a las mineras canadienses para que nos ayudaran a proteger el territorio.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Los pobres son los codiciosos. Si lo piensas, para ser rico, necesitas dar algo. Debo producir libros, juegos, comprar terrenos, ofrecer viviendas, ofrecer trabajos. Pero la gente codiciosa no produce nada.",
    "author": "Robert Kiyosaki",
    "info_author": "",
    "comment": "",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Siguen las fallas en abasto de medicamentos a pesar de las instrucciones presidenciales…",
    "author": "Patricia Armendáriz",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Casi nadie contrataría a un niñero varón para que cuidara a sus hijos, ¿y sin embargo damos hijos en adopción a parejas masculinas? ¿Tiene sentido?",
    "author": "Matt Walsh",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "No entiendo, hasta ahorita, después de 35 años, por qué nos están atacando tanto cuando eran otros tiempos.",
    "author": "Martha Rodríguez Ortiz, asesora de tesis de Yasmín Esquivel",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "El comunismo lo inventó un burgués, las leyes racistas en EEUU las abolieron los blancos. Piénsalo.",
    "author": "JPelirrojo, influencer español",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "01/2023",
    "text": "Cuánta gente perfecta en Twitter condenando a la ministra Yasmín Esquivel. No conciben la posibilidad de que alguien caiga en una conducta indebida. No tienen entonces capacidad de perdonar una falta.",
    "author": "Federico Arreola",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "Quieren que el gobierno les pague los condones. Quieren que el gobierno les pague el aborto. Están a nada de pedir que el gobierno les pague la peda y las prostitutas o los prostitutos, según el caso.",
    "author": "Christian Camacho, sobre la propuesta de garantizar la gratuidad de los preservativos.",
    "info_author": "",
    "comment": "Preservativos, ergo, peda y prostitución. ¿En qué tugurio tomó clases de educación sexual? ¿Con qué chiste de Pepito se dio por formado en materia de sexo y lógica? Sólo una mirada muy depravada se permite menospreciar a tal grado los paseos por los bosques deleitosos de la concupiscencia."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "[Sobre los deudores morosos]. Me pasa cada mes con miles de personas y luego terminan olvidándose que cuando necesitaron ayuda, fuiste el único que les dio la oportunidad; se convierten en tus enemigos, hasta que vuelven a necesitar dinero… entonces regresan.",
    "author": "Ricardo Salinas Pliego, usurero  filántropo",
    "info_author": "",
    "comment": "Como los hacendados de los siglos pasados no tuvieron Twitter, no pudimos enterarnos de que las Tiendas de Raya eran instituciones de caridad."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "La política de seguridad dio resultados [...] Los principales indicadores de criminalidad iban a la baja al terminar mi gobierno.",
    "author": "Felipe Calderón",
    "info_author": "",
    "comment": "En los últimos minutos del partido metimos un gol. De mantenerse la tendencia, hubiéramos remontado ese complicado 9-1 en contra..."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "La señora presidenta de la Corte, para hablar en plata, está por mí de presidenta…",
    "author": "AMLO",
    "info_author": "",
    "comment": "Al no ponerla yo, soy yo quien la pone. El humanismo mexicano como la posibilidad de trasladar a la política la dialéctica de la canción ranchera: cuando me cambiaste por otro, fui yo quien te dejó. O bien: Estás por que yo quiero que te quedes, y a la hora que yo quiera te relevo. Firma: el Alfa que en sus ratos libres también chambea de Omega."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "Ser incómodo para los tiranos es lo más significativo que me ha pasado.",
    "author": "Chumel Torres",
    "info_author": "",
    "comment": "Aquí incomodando, dijo la hormiga. Aquí construyendo la paz en Chiapas, dijo Maná. Aquí luchando por la emancipación de la mujer proletaria, dijo Paris Hilton."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "[Sobre la condena de García Luna] ¿Verdad que sí ha habido cambios? Estas cosas no se veían. [...] Vamos a seguir avanzando en la transformación…",
    "author": "AMLO",
    "info_author": "",
    "comment": "Aquí arando, dijo la hormiga, ¿Verdad: Señor Borrón-y-Cuenta-Nueva, Don Olvido-No-Pero-Perdón-Sí, Míster Que-Se-Haga-Una-Consulta...?"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "02/2023",
    "text": "Ovidio [Guzmán] desafía la explicación obradorista de que el crimen es resultado de la pobreza. Creció como niño pijo en el Pedregal y estudió primaria en el Ceyca, la escuela más fresa del sur. Luego arruinó su vida siguiendo al padre.",
    "author": "Pablo Majluf",
    "info_author": "",
    "comment": "Lo llamaremos falsacionismo en esteroides: si encontramos un cisne negro, le escribimos a Karl Popper para notificarle que los cisnes blancos no existen. PD.- Avísenle a los cientos de miles de presos que a lo mejor pertenecen a la clase media."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Pienso que Elon Musk está viendo lo que nosotros no. Invertirá en México en un tiempo en el que inversionistas nacionales y extranjeros prefieren ESPERAR. Musk ya vió la manifestación nacional ciudadana del 26 de febrero y sabe que se junta con el ocaso de MALO.",
    "author": "Pedro Ferriz de Con",
    "info_author": "",
    "comment": "¿Ya vieron? La gente de bien genera empleos hasta cuando marcha en domingo."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Vuelan vuelan hacia los cielos las aeronaves con libertad/Varios destinos en territorio, también con rumbo internacional...",
    "author": "Himno del Aeropuerto Internacional Felipe Ángeles",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Esto [el himno del AIFA] es casi fascista.",
    "author": "Joaquín López Dóriga",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Que nunca más tengamos institutos electorales costosos e imparciales a costa del pueblo.",
    "author": "Morena",
    "info_author": "",
    "comment": "Nunca más instituciones imparciales. Nuestra lucha es contra el diccionario y por la inimparcialidad"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Me preocupa mi familia, mi trabajo, mi país… tengo la misma sangre que tú.",
    "author": "Gustavo de Hoyos",
    "info_author": "",
    "comment": "Está muy bien saberlo si nos está convocando a una transfusión sanguínea. Lo que nos preocupa son los intereses de clase y ahí sí usted parece ser del tipo receptor universal de plusvalía y adivine quiénes son los donadores..."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Esas no van a venir.",
    "author": "Manuel Bartlett, en Pasta de Conchos, sobre cinco viudas ya fallecidas de los mineros sepultados.",
    "info_author": "",
    "comment": "Y bueno, si renuncio al sentido del humor con qué quieren que me quede. ¿Mi inteligencia? ¿Mi honestidad?."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2023",
    "text": "Pueden contestarme lo que quieran, pero no tienen pruebas, son calumniadores, mentirosos. En México no se tortura, no es como antes, que ellos se quedaban callados y nunca decían nada. En México no hay más masacres, en México el Estado ha dejado de ser el principal violador de los derechos humanos.",
    "author": "AMLO, en respuesta al Departamento de Estado de EU.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "La condena de Cristo por un grupo de acarreados nos deja claro el peligro social de las consultas populares, que usa AMLO para decidir varios asuntos, como la construcción de una cervecería en Mexicali…",
    "author": "Luis Pazos, en su artículo “Cristo, víctima del populismo”.",
    "info_author": "",
    "comment": "Silogismos Cuánticos lo lleva de Jerusalén a Mexicali en menos de lo que el gallo prescinde tres veces del sentido común. Reconózcanos por nuestro lema: “Si uno por uno es uno, dos por dos, dos”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Tomen su lugar en la batalla y hagan lo que saben hacer, para bien o para mal. Queremos constancia de mayoría, no de buena conducta. Salgan y ganen la elección.",
    "author": "Alejandra del Moral, candidata a la gobernatura del Estado de México.",
    "info_author": "",
    "comment": "No es que uno sea miedoso. Pero viniendo de una candidata del PRI esto está para arenga de barco pirata a punto de atracar."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Quienes argumentan que “la mañanera no se toca” [...] se asemejan demasiado a robespierianos cortando cabezas, estalinistas asesinando disidentes, nazis persiguiendo judíos, inquisidores torturando a paganos, y hombres quemando a mujeres en la plaza pública.",
    "author": "Denisse Dresser",
    "info_author": "",
    "comment": "Pero la historia sabrá poner nuestros dignos artículos lado a lado con  los gritos de horror de nuestros compañeros de calvario: inocentes decapitados, disidentes masacrados, judíos asesinados, paganos torturados, mujeres quemadas, también demasiado semejantes a nosotros."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Esto es una mierda de nivel comunista. Esto es algo que haría a Mao, a Stalin, a Pol Pot, sonrojarse.",
    "author": "Donald Trump Jr, sobre el arresto de su padre.",
    "info_author": "",
    "comment": "Es sabido que Mao, Stalin y Pol Pot se sonrojaban cuando se enteraban de que se cometía algún arresto cuestionable."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Guadiana las va a meter la pinga. Y lo digo claro, y lo digo fuerte.",
    "author": "Pedro Haces, líder sindical, durante un mitin en apoyo a Armando Guadiana.",
    "info_author": "",
    "comment": "Compañero, evite esas vulgaridades. Se dice pene. “Les va a meter el pene”. Basta de machismo."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Hermano Andrés, has venido a levantarnos del polvo. [...] Ese caballo de fuego, veloz, extraordinario, a quien trasplantaste tu alma, con su coraza metálica traspasará brechas del progreso sin fronteras para que al fin llegue la justicia.",
    "author": "Layda Sansores, recién levantada del polvo, en texto dedicado al Tren Maya y al presidente.",
    "info_author": "",
    "comment": "Agárrate poema de Gilgamesh que la nueva épica nacional viene con todo..."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "04/2023",
    "text": "Por mucha tragedia que sea la muerte de migrantes, no debe minimizarse que fue un accidente provocado por ellos mismos al incendiar colchones como protesta para evitar ser deportados, provocando una intoxicación masiva.",
    "author": "Nacho Rodríguez, 'El Chapucero' ",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Confirmen si Disney la está cagando bien duro ? Cuando vi la de peter pan con los niños me pareció que pusieron de peter pan a un niño feo para que muchos se identifiquen pero pues no es aspiraciónal estar todo culero. Los niños no entienden eso ! Déjenlos vivir su infancia bonita.",
    "author": "Poncho De Nigris, actor y aparentemente pedagogo.",
    "info_author": "",
    "comment": "A usted le parecía simplona la canción de “Que se mueran los feos…”? Pues resulta que es el encefalograma musicalizado de algunos adultos que están para decirle a los niños lo que entienden y lo que no.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Si se tiene que colocar un muro en la frontera sur, lo vamos a hacer.",
    "author": "Carlos Leal",
    "info_author": "",
    "comment": "La derecha moderna es cosmopolita. Está abierta a las ideas tontas de cualquier parte del mundo."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "También hay que tener obligación en las mujeres en el sentido de la vestimenta [...] Claro, la mujer muchas veces provoca y entonces después no se aguanta.",
    "author": "Pedro Haces, exsenador de Morena y líder de la Confederación Autónoma de Trabajadores y Empleados de México.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Los perritos no causan el hambre en el mundo, sino los padres que encargan hijos sin poder -o querer- mantenerlos luego. ¿Por qué la Iglesia Católica nunca los critica a ellos?",
    "author": "Paco Calderón",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Muchas felicidades Fondo de Cultura Económica; la izquierda progre recuperó su editorial! No importa que todos los días critiquen a la 4T. Ya sólo les falta G. Niebla o ya de plano: Lilly Tellez, Javier Lozano o Chumel Torres. Total, todos ellos comparten el odio y desprecio sobre el gobierno de México.",
    "author": "Marx Arriaga, sobre la publicación del libro de Luis Hernández Navarro.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Los países más desarrollados no alcanzaron su riqueza con expropiaciones, sino respetando los derechos de propiedad adquiridos de manera legítima por sus habitantes…",
    "author": "Sergio Martínez, economista",
    "info_author": "",
    "comment": "Declaraciones que que renovarán los estudios sobre la modernidad: “Haciendo abstracción de algunos eventos intrascendentes entre 1492 y el día de la fundación de la OCDE…”"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2023",
    "text": "Este veredicto es una vergüenza. Una continuación de la mayor caza de brujas de todos los tiempos.",
    "author": "Donald Trump, sobre su condena por abuso sexual",
    "info_author": "",
    "comment": "La mayor caza de brujas de todos los tiempos fue contra un señor al que se le impuso una multa por abusar sexualmente de una mujer."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "Que quede claro: el grito de “puto” NUNCA fue un grito homofóbico. Era una simple expresión folclórica contra el arquero rival.",
    "author": "Luis Felipe Calderón",
    "info_author": "",
    "comment": "Clarísimo. ¿Qué tiene de homofóbico hacer de una preferencia sexual un insulto? Es más, la homofobia también es una simple expresión folclórica. El respeto a la dignidad de las personas no puede estar por encima de los fundamentos de nuestro ser nacional.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "México se escribe con “M” de madre, con “M” de mujer. Nuestra patria libre y soberana, por voluntad de su pueblo, está escribiendo el capítulo de la igualdad…",
    "author": "Claudia Sheinbaum",
    "info_author": "",
    "comment": "Lo de las complicidades ortográficas entre “mujer” y “madre” está para promocional de la Liga de la Decencia."
  }, 
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "Llegaron a decir que no había existido ‘el Pípila’, porque nadie podría cargar una piedra tan pesada, o sea, quitarle hasta la imaginación a nuestro pueblo, el derecho a la esperanza, como si todo fuese racional y no hubiese lo místico. Y así muchísimas cosas. Que Siete Leguas no era caballo, sino yegua, nada más que ahí sí no pudieron porque el corrido, no me gusta la palabra, pero corrido tiene más peso que el pasaje histórico. Y sí, se argumentó muchísimo, que era yegua porque, todavía hasta hace poco, escuché una narración que cuando Villa pacta la paz con Adolfo de la Huerta ― que fue un buen presidente don Adolfo de la Huerta […]. Pero, bueno, todo esto. No, las ofensas, hasta en películas de los cineastas o en la ondita, progres, o en la ondita contra Hidalgo, y así…",
    "author": "AMLO, en respuesta a una pregunta sobre el proceso interno de Morena.",
    "info_author": "",
    "comment": "Lo místico debe ser aquella región donde habita la coherencia de esta respuesta",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "Las olas de calor de cada año son el orgasmo progre de los ambientalistas. En estas fechas siempre salen con su perorata de que nos estamos acabando el mundo y que el planeta llora. Puras mamadas de gente pendeja.",
    "author": "Cristian Camacho",
    "info_author": "",
    "comment": "En el mundo de los negacionistas, juntar dos o tres palabrotas equivale a una publicación dictaminada a doble ciego.",
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "Mientras en México tengamos un gobierno mediocre como el de Morena y López Obrador [...] la Selección Mexicana no ganará. [...] Aquí te pongo los últimos 5 mundiales. Podrás ver cómo los países que ganan son prósperos. Yo quiero un México próspero en donde puedas salir tranquilo, estés bien alimentado [...]. Un México en el que nuestra Selección mexicana pueda ser mejor.",
    "author": "Kenia López Rabadán, senadora del PAN",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2023",
    "text": "La Nueva Derecha es la resurrección de Dios en la cultura de Occidente.",
    "author": "Raúl Tortolero",
    "comment": "",
    "info_author": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "ERES PIRRICO, ERES CHURUMBEL, ERES APRENDIZ DE MAGO, FUTUROLOGO Y DEMAS... YERBAS. NI ES CLAUDIO… NI ES XOCHITL.... NI ES FOX… NI ES ANAYA… SERA MELON, SERA SANDIA, SERA TU VIEJA DEL OTRO DIA, DIA...",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "Ojalá Fox hubiera conocido las drogas hace treinta años. Qué presidente nos hubiéramos ahorrado; qué marihuano nos perdimos.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "Y si traemos a los mercenarios del Wagner Group a combatir el narco en México? Quizá sea una discusión que debamos tener a profundidad.",
    "author": "Javier Tejado Dondé, columnista de El Universal",
    "info_author": "",
    "comment": "Cincuenta mil mercenarios rusos es lo que le falta a nuestro cocktail pacificador. Si alguien propone que México contrate a los Looney Tunes, seguirá siendo una idea más sensata que esta columna.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "Para entender a López Obrador hay que irse más atrás. [...] López Obrador no está tratando de recuperar al PRI, está tratando de recuperar el tiempo de Santa Anna. Es muy probable que ni siquiera lo entienda porque sus conocimientos de historia son los del libro de texto gratuito, pero eso exactamente es lo que está haciendo.",
    "author": "Macario Schettino",
    "info_author": "",
    "comment": "Y dice “exactamente” porque el rigor es un valor irrenunciable. La compra de Deer Park es como la venta de La Mesilla. Se sabe que planea hacerse llamar: “Su Amleza Obradorísima”."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "El INE ya es como la Santa Inquisición.",
    "author": "AMLO",
    "info_author": "",
    "comment": "El presidente prepara tremendo eslógan: soy el abuelito de todas las brujas que nunca pudieron quemar."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "El golpe militar, terrible, y la muerte transitoria de la democracia fueron en verdad lamentables. Pero la responsabilidad directa pertenece claramente al gobierno de la Unidad Popular y a Salvador Allende…",
    "author": "Gabriel Quadri",
    "info_author": "",
    "comment": "Oh el arte de la asignación creativa de responsabilidades. Allende obligó a Pinochet a levantarse en armas.  Es como decir que la culpa de las declaraciones de Quadri las tienen el teclado y el micrófono."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "Pero lo mejor es que los liberen; si no, los voy a acusar con sus papás y con sus abuelos. Ya ven que salió un Amlito. Ah, ya no puedo hablar de eso, que habla el Amlito y dice: ‘Lo que diga mi dedito’. [...] ¿Adónde hay? ¿Tienes uno? A ver, pásalo…",
    "author": "AMLO, sobre los dieciséis trabajadores secuestrados por el crimen organizado.",
    "info_author": "",
    "comment": "La estrategia de seguridad del presidente debería incluir el compromiso de dejar de hacer chistes tontos."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2023",
    "text": "Es una campaña en contra del ejército de México, sin fundamento. Es una campaña para socavar, para debilitar a las fuerzas armadas.",
    "author": "Felipe Calde... AMLO, sobre el informe del GIEI.",
    "info_author": "",
    "comment": ""
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "Plenaria” es otra de las palabras que usted puede encontrar en todos los libros y en todos los temas. “Plenaria” es una palabra total. O sea, si lo queremos reducir a un sinónimo, es \"total\", totalitario. Es un término hegemónico, que habla de un solo bloque, de un gobierno único.",
    "author": "Otoniel Martínez, conductor de Tv Azteca, sobre el carácter comunista de los libros de texto gratuitos.",
    "info_author": "",
    "comment": "Comunismo viene de común, o sea, común y corriente, como quien dice sin clase, chafa. Por eso a Marx odiaba las clases y la ropa de marca y dijo que no hay que comprar Iphone. Quien no haga análisis eitmológicos no entenderá nada de nada."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "La embajada argentina en Israel la voy a mudar de Tel Aviv para llevarla a Jerusalém. Porque cuando el Uno le ordenó a Moisés que rompa las primeras tablas de la ley, la primer palabra que pronunció fue Jerusalén. Y ahí fue donde el rey David estableció la capital.",
    "author": "Javier Milei",
    "info_author": "",
    "comment": "La que se armaba si al Uno, nomás por fregar, se le ocurría decir Coatzacoalcos. Pd. Si va en serio lo de orientar nuestras leyes en libros religiosos antiguos, proponemos incorporar “no cocerás el cabrito en la leche de su madre” y “tu campo no sembrarás con mezcla de semillas” (o sea: “milpa no, monocultivo sí”. A ver si no resulta que la redacción del Levítico estuvo patrocinada por Monsanto)."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "ABER baboso ignorante!",
    "author": "Pedro Ferriz Híjar",
    "info_author": "",
    "comment": "Eso te pasa por no a ver estudiado!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "No somos perfectos los priístas, pero damos resultados",
    "author": "Alejandro Moreno, líder nacional del PRI.",
    "info_author": "",
    "comment": "Por ejemplo, en el sexenio pasado logramos el record de gobernadores encarcelados. Lo de no ser perfectos lo ejercemos a cabalidad."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "Para darle una salida definitiva al desabasto, vamos a proponer, les voy a proponer a los del sector Salud que se tenga una especie de farmacia donde se cuente… Una farmacia aquí en la Ciudad de México, un almacén con todas, todas, todas las medicinas, todas, todas las medicinas del mundo, en cantidades razonables para que cuando falte en un hospital, ahí, como un banco de reserva de medicamentos, y lo vamos a hacer.",
    "author": "AMLO",
    "info_author": "",
    "comment": "Cómo no se nos había ocurrido que la solución al desabasto es tener todas las medicinas. Afortunadamente el presidente es pacifista, que si quisiera volverse potencia militar luego luego propondría tener un arsenal con todas, todas las armas atómicas del mundo, pero todas todas, y a ver quién lo para."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "Yo no les diría errores. Yo les diría áreas de oportunidad.",
    "author": "Marx Arriaga",
    "info_author": "",
    "comment": " -Por qué no llegaste a dormir anoche? - Fíjate que le encontré unas áreas de oportunidad a mi personalidad."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "Ojalá Xóchitl nos cubra eso. Que los huevones no caben en el gobierno y tampoco en el país. Ya se acabó que estés recibiendo programas sociales. ¡A trabajar cabrones!",
    "author": "Vicente Fox",
    "info_author": "",
    "comment": "Fox presenta: “Los beneficiarios de programas sociales son unos holgazanes y otros eslóganes para ganarnos la simpatía de la gente”. Pd.- Ah, la pensión vitalicia a expresidentes sí devuélvanla por favor.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2023",
    "text": "Zurdos de mierda: somos superiores productivamente, somos superiores moralmente, somos superiores estéticamente\".",
    "author": "Javier Milei",
    "info_author": "",
    "comment": "Eso sí ofende. La izquierda nunca reivindicó como suya la guapura, pero nunca nos habían dicho feos. Tendremos que proponer el acceso público y gratuito a los servicios de peluquería."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Viva Allende! ¡Viva Morelos! ¡Viva el erótico pueblo de México!",
    "author": "Jesús Flores, alcalde de Huatabampo, durante la conmemoración del grito de independencia.",
    "info_author": "",
    "comment": "Vivan los concupiscentes empeños de las masas! ¡Vivan los eros que nos dieron líbido!."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Gracias Ángel de la Independencia, gracias por esta independencia que tenemos, por esta libertad, porque gracias a esta libertad hoy está Sandra Cuevas hablando como se debe hablar.",
    "author": "Sandra Cuevas",
    "info_author": "",
    "comment": "Bonita conversación entre una estatua y la multitud de personalidades alojadas en el ego de Sandra Cuevas."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Naca, mugrosa, pobre enana. Amarra a tu perra, no traigas a tus sirvientas a la cámara.",
    "author": "María Clemente, diputada de Morena",
    "info_author": "",
    "comment": "La verdadera lucha de la izquierda es por democratizar el derecho a ser clasistas."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Meditación mañanera… Pregunta: Porque los izquierdos son tan amargosos? Respuesta: Está cabrón ser feliz cuando inicias cada día pensando cómo robarle al prójimo el fruto de su trabajo y odias el éxito y la prosperidad ajena.",
    "author": "Ricardo Salinas Pliego, filósofo",
    "info_author": "",
    "comment": " Oh las meditaciones que tardan dos segundos en llegar a insospechadas conclusiones."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Debemos restablecer el monumento a Cristobal Colón en el Paseo de la Reforma…",
    "author": "Gabriel Quadri",
    "info_author": "",
    "comment": "Gabriel Quadri, siempre al servicio de las prioridades nacionales.."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Fue un golpe de Estado no tradicional.",
    "author": "Sebastián Piñera, expresidente de Chile, sobre el estallido social de 2019",
    "info_author": "",
    "comment": "Sin torturas, desaparecidos, asesinatos…. toda una falta de respeto a la tradición. Es más: lo de Pinochet fue más bien una protesta ciudadana no tradicional."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "No odias los lunes, odias tu vida y sólo es lunes.",
    "author": "Chumel Torres",
    "info_author": "",
    "comment": "Lo agobia la idea de pararse a las 6 de la mañana y pasar dos horas en el transporte público para llegar a un trabajo malpagado? No se preocupe, los portavoces de la encumbrada frivolidad están aquí para prodigarle lecciones de vida."
  },
  {
    "points": 0,
    "region": "",
    "hashtags": [],
    "date": "09/2023",
    "text": "Estos cien kilómetros de tubo... Si tu vas en tu carro y le pisas a cien kilómetros por hora, te puedes echar hora y media.",
    "author": "Samuel García, gobernador de Nuevo León",
    "info_author": "",
    "comment": "Bueno, el problema estaba complicado. Va otro más al nivel del gobernador: si Pedro tiene 3 manzanas, ¿cuántas manzanas tiene?."
  },
  {
    "text": "Si hubiera un virus letal, ¿no creen que ya nos hubiéramos muerto todos?",
    "author": "Paty Navidad",
    "info_author": ", actriz y epidemióloga.",
    "comment": "La peste negra tampoco era letal. Sobrevivió como media Europa.",
    "region": "nacional",
    "points": 0,
    "date": "01/2021",
    "hashtags": ["Epidemiología"]
  },
  {
    "text": "La Senadora tiene una obsesión por el aborto. Para ella el Aborto es la solución a todos los problemas de la mujer en México, lamentable. No conozco NI UNA iniciativa de la Senadora a favor de la mujer embarazada en estado de vulnerabilidad.",
    "author": "Carlos Leal",
    "info_author": "diputado de Nuevo León, a propósito de la senadora Patricia Mercado.",
    "comment": "O díganme: ¿qué tiene que ver el aborto con una mujer embarazada en estado de vulnerabilidad?",
    "region": "nacional",
    "points": 0,
    "date": "",
    "hashtags": [
      "En defensa de las damitas"
    ]
  },
  {
    "text": "El atentado que sufrió García Harfuch deja en evidencia que querían asesinarlo.",
    "author": "Raymundo Riva Palacio",
    "info_author": ", periodista y detective.",
    "comment": "¿De veras? Nada más le dispararon 400 veces. ¿Ya se lo comentó a los detectives?",
    "region": "nacional",
    "points": 0,
    "date": "07/2020",
    "hashtags": [
      "Hazañas de la inferencia",
      "Premio Sherlock Holmes"
    ]
  },
  {
    "text": "Están recibiendo billetes y los están contando, pero no sabemos si es la nómina del senado.",
    "author": "Sergio Sarmiento",
    "info_author": ", acerca del video que muestra a funcionarios públicos recibiendo fajos de dinero en efectivo.",
    "comment": "La víctima presenta cuatro heridas de bala en la cabeza. No descartemos que se suicidó.",
    "region": "nacional",
    "points": 0,
    "date": "08/2020",
    "hashtags": [
      "Premio Sherlock Holmes"
    ]
  },
  {
    "text": "¿De dónde obtiene su conocimiento?, pregunta un internauta a Paty Navidad: “De los libros, documentales, y del mismo internet, ésta todo, sólo hay que saber buscar para encontrar información que no es la “oficial” por así decirlo. También de la experiencia y vivencia personal, eso tiene mucha más contundencia y veracidad, lo sé y me consta.”",
    "author": "Paty Navidad",
    "info_author": ", actriz y bióloga autodidacta.",
    "comment": "El método científico es googlear y tener vivencias.",
    "region": "nacional",
    "points": 0,
    "date": "",
    "hashtags": []
  },
  {
    "text": "Se pregunta amlo: ¿qué hacemos con los ricos.”? Yo le contesto: esos “ricos” según el S.A.T., tienen contratados a 22 millones de empleos, mismos que van desapareciendo gracias a las políticas suicidas del presidente. Si tuviéramos el doble de ricos, tendríamos el doble de empleos.",
    "author": "Francisco Martín Moreno",
    "info_author": "",
    "comment": "",
    "region": "nacional",
    "points": 0,
    "date": "05/2020",
    "hashtags": [
      "Economía"
    ]
  },
  {
    "text": "Oración para exorcizar el feminismo de una mujer: Te voy a hacer el amor como Dios manda hasta hacerte una panzota hermosa de 9 meses, no tendrás la necesidad de trabajar el resto de tu vida, vivirás como princesa en la medida de lo posible y vas a contar conmigo siempre.",
    "author": "Christian Camacho",
    "info_author": "",
    "comment": "Más que al feminismo, esta oración amenaza con aniquilar la heterosexualidad de las mujeres.",
    "region": "nacional",
    "points": 0,
    "date": "09/2020",
    "hashtags": []
  },
  {
    "text": "Antorchas en el Zócalo quiere López el 15 de septiembre. Evocación del nazismo.",
    "author": "Gabriel Quadri",
    "info_author": ", diputado.",
    "comment": "De lo que se sigue que yo debo ser una evocación de la resistencia antinazi.",
    "region": "nacional",
    "points": 0,
    "date": "09/2020",
    "hashtags": [
      "LaHistoriaEsMiPasión",
      "ElRigorEstáSobrevalorado"
    ]
  },
  {
    "text": "Más de 40 mil muertos por Covid-19! Miles de hijos, esposas, esposos, nietos… por la estupide de un ignorante que llegó al poder! Ya entendieron que es más peligroso en el poder un analfabeta, que la bomba atómica; más peligroso que un dictador como Mussolini, Hitler y Franco?",
    "author": "Ricardo Alemán",
    "info_author": ", periodista.",
    "comment": "",
    "region": "nacional",
    "points": 0,
    "date": "07/2020",
    "hashtags": []
  },
  {
    "text": "Decir que el pobre es pobre porque el rico es rico, es como decir que el enfermo está enfermo porque el sano está sano. Son dos cosas que no tienen nada que ver. La riqueza NO es un juego de suma cero.",
    "author": "Ricardo Salinas Pliego",
    "info_author": "",
    "comment": "Si el rico se enriquece cobrando intereses usurarios al pobre, algo de relación sí hay.",
    "region": "nacional",
    "points": 0,
    "date": "07/2020",
    "hashtags": [
      "Economía"
    ]
  },
  {
    "text": "Lamento los muertos, lo lamento. Pero todos nos vamos a morir un día, aquí todos vamos a morir. No sirve de nada huir de eso, huir de la realidad. Tienen que dejar de ser un país de maricas.",
    "author": "Jair Bolsonaro",
    "info_author": ", presidente de Brasil, acerca de la pandemia del Covid-19.",
    "comment": "Ya sé que ustedes no tienen acceso a los servicios de salud que yo disfruto, pero eso no es pretexto para que su cobardía arruine mis indicadores macroeconómicos, bola de cobardes.",
    "region": "internacional",
    "points": 0,
    "date": "05/2020",
    "hashtags": [
      "Epidemología humanista"
    ]
  },
  {
    "text": "Un capitalista te pedirá que lo dejes trabajar en paz. Un socialista te pedirá que trabajes y le entregues parte de tu dinero.",
    "author": "Sergio Negrete Cárdenas",
    "info_author": ", aparentemente historiador.",
    "comment": "La United Fruit fue una misión de paz",
    "region": "nacional",
    "points": 0,
    "date": "11/2020",
    "hashtags": [
      "Economía",
      "Historia del capitalismo"
    ]
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2020",
    "text": "Más de 40 mil muertos por Covid-19! Miles de hijos, esposas, esposos, nietos… por la estupide de un ignorante que llegó al poder! Ya entendieron que es más peligroso en el poder un analfabeta, que la bomba atómica; más peligroso que un dictador como Mussolini, Hitler y Franco?",
    "author": "Ricardo Alemán",
    "info_author": ", periodista.",
    "comment": ""
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "06/2020",
    "text": "El demonio existe en plena pandemia, intentando llevar a cabo investigaciones para vacunas y para curaciones. Nos encontramos con la dolorosísima noticia de que una de las vacunas se fabrica a base de células de fetos abortados. Eso es despreciar al hombre mismo... Primero se le mata con el aborto, y después se le manipula para: “ay qué bueno, mira qué bien, ya tenemos una vacuna”.",
    "author": "Antonio Cañizares",
    "info_author": ", Arzobispo de Valencia",
    "comment": "Increíble que en pleno siglo XXI la ciencia siga creyendo en las vacunas."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2020",
    "text": "IMAGÍNENSE la cena de gala, a los empresarios mexicanos, a los embajadores de ambos países, Ebrard y los invitados gringos -TODOS ENGLISH SPEAKING-, cuando estén traduciendo a AMLO pero no entienda los chistoretes de TRUMP, todos riendo y él con cara de WHAT. ¿Sentirán vergüenza?",
    "author": "Ma. Elena Pérez-Jaén",
    "info_author": "",
    "comment": "En el siguiente cuadro Susanita sonríe despreocupada mientras Mafalda no puede creer lo que acaba de escuchar."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "07/2020",
    "text": "Parece que a los zurditos les molestó mucho que saliéramos en nuestros carros, no soportan ver la superioridad estética y moral de nuestra marcha frente a las porquerías violentas y sucias que ellos hacen cuando protestan.",
    "author": "Christian Camacho",
    "info_author": "",
    "comment": "Guácala ser pobre y tener que ir a la marcha en microbús."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2020",
    "text": "En Dinamarca no funcionaría el clientelismo de amlo.",
    "author": "Francisco Martín Moreno",
    "info_author": ", compartiendo la información (equivocada) de que \"En Dinamarca toda persona que recibe algún tipo de ayuda social está inhabilitada para votar\".",
    "comment": ""
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2020",
    "text": "[Leona Vicario] también dio dinero y no la grabaron. Me gustaría ver el video de cuando Leona Vicario daba dinero para que todos pudieran comer en los campamentos y lucháramos por la independencia.",
    "author": "Beatriz Gutiérrez Müller",
    "info_author": ", en respuesta a los videos que muestran a Pío López Obrador recibiendo sobres con dinero en efectivo.",
    "comment": "Leona Vicario hizo tanto por México que hoy es digna de ser comparada con el hermano del líder de nuestro movimiento. (Pd.- En rigor, la ausencia de grabaciones sugiere que la prócer pudo haber hecho sus contribuciones vía SPEI)."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2020",
    "text": "Como cuando tú vieja agarra tú cel y le escribe a tus amigos para que ya no te inviten al pedo.",
    "author": "Pedro Ferriz Híjar",
    "info_author": "",
    "comment": "Qué menso, se le olvidó acentuar 'tús'." 
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "08/2020",
    "text": "¡Chinga tú madre!",
    "author": "Pero Ferriz Híjar",
    "info_author": "",
    "comment": "O sobra un acento o falta ir a terapia."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "En fin mis queridos hĳos de… Me he dado cuenta que… Muchos de sus papás y mamás… Desgraciadamente… ¡No tienen madre! Y una sugerencia: Cambien el nombre de su partido. Les sugiero: PUP. (Partido Único de P…)",
    "author": "Carlos Alazraki",
    "info_author": "",
    "comment": "Es enternecedor que Carlos Alazraki le encarge escribir sus columnas a su sobrinito de 5 años."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "Hasta entre los perros hay razas diversas. Hay unos perros que los agarras de aquí, que tienen tan poco pedigrí que todavía no los tocas y ya están chillando, hay otros llenos de pulgas. ¿Crees que yo me voy a poner a discutir con esos cuates? [...] No es un tema de arrogancia, es un tema de experiencia.",
    "author": "Pedro Ferriz de Con",
    "info_author": "",
    "comment": ""
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "¿Qué quiere Morena? Iniciar el establecimiento de un Estado comunista en México. Así de sencillo.",
    "author": "Carlos Mota",
    "info_author": "",
    "comment": "Sin la socialización de los medios de producción, pero un Estado comunista. Vaya, sin reforma fiscal, pero de que quieren un Estado comunista no hay duda"
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "Los mexicanos no debieron sacralizar el precepto de la “lucha contra la desigualdad”. Pero sus culpas pudieron más que su amor propio...",
    "author": "Carlos Mota",
    "info_author": "periodista.",
    "comment": "No es para tanto: seguimos siendo un país profundamente desigual... algo de amor propio nos queda. Y mire qué bien estamos, no como esos escandinavos que tanto deben despreciarse" },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "Querer combatir la desigualdad es propio de mentes torcidas. La desigualdad es inherente a neustra condición de vida. Qué tontos fueron quienes tragaron el cuento de que hay que combatirla. Ahora no se digan sorprendidos por las ocurrencias comunistas de Morena. Incongruentes.",
    "author": "Carlos Mota",
    "info_author": "",
    "comment": "Mire qué bien le va los países más desiguales del mundo: Zambia, Honduras, Haití, Namibia..."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "05/2020",
    "text": "¿Qué quiere AMLO? ¿Hacia dónde va el país? Los hechos apuntan a que vamos hacia el socialismo caduco.",
    "author": "Pablo Hiriart",
    "info_author": "periodista.",
    "comment": "¡Un fantasma recorre la imaginación del columnista! Por 'los hechos' me refiero a lo que fantaseo que puede llegar a suceder una vez que hacemos abstracción de los hechos. Lo llamo empirismo imaginario."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Nuestro mayor empoderamiento es reconciliarnos con nuestra esencia de mujer. Como dadoras de vida.",
    "author": "Elsa Méndez",
    "info_author": ", diputada local de Querétaro",
    "comment": "Suena Mujeres Divinas para ambientar el fin de las hostilidades con la esencia y su relocalización en el útero."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Los hombres claro que sufrimos acoso por la calle de noche (principalmente de prostitutas que pululan por las zonas de marcha), y además tenemos 3 veces más probabilidades de sufrir un ataque u homicidio. No pasa nada por sentirse incómodo de vez en cuando, así es la vida.",
    "author": "Alonso Mendoza",
    "info_author": ", candidato al Congreso de Madrid por VOX.",
    "comment": "¡Ah, las prostitutas, ese foco de inseguridad para los hombres! Además, los hombres ejercemos la violencia contra todos por igual: que las damitas no vengan a quejarse con su mujeril sufrimiento identitario."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Si usted es candidata (...) haga cosas que realmente hacen o quieren hacer las mujeres. ¿Qué son esas cosas? Muéstrese tierna, compasiva, amorosa. Ayude a su familia, platique su día en sus entrevistas, el reto que significa para usted llevar la casa, los hijos (si es que los tiene) y la candidatura. (...) Lo peor que puede hacer usted como candidata es hacerle caso a lo que los medios de comunicación y las feministas dicen que quieren las mujeres. Eso es lo que ELLOS quieren escuchar y créame que nada tiene que ver con lo que las mujeres mexicanas son.",
    "author": "Christian Camacho",
    "info_author": "",
    "comment": "Amiga candidata: ¿quiere saber lo que la mujer mexiana es y quiere? Pregúnteme."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Ahora con la simulación sobre el feminismo, empiezo a escuchar “Rompa el pacto, rompa el pacto”. Les digo, sinceramente, y no miento... me enteré de lo que era eso hace cinco días. Le dije a mi esposa, oye, ¿qué es esto de “rompa el pacto”? Y ya me dijo: rompa el pacto patriarcal. O sea, deja de estar apoyando a los hombres. ¿Y saben qué sucede? Que son expresiones importadas. Copias, o sea...¿Qué tenemos nosotros que ver con eso, si nosotros somos respetuosos de las mujeres, de todos los seres humanos?",
    "author": "AMLO",
    "info_author": "",
    "comment": "Lo importante es que usted siga hable y hable del tema que sea. Cuando uno no entiende algo lo mejor es explicarlo en cadena nacional."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Antes no habían esas protestas, empezaron con nuestro gobierno porque valiéndose de un movimiento justo noble [los conservadores] se aprovechan para lanzarse en contra de nuestro gobierno...",
    "author": "AMLO",
    "info_author": "",
    "comment": "Algunos revisionistas quisquillosos sostendrán que el feminismo existió antes de 2018"
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Yo creo que el aborto es un crimen mucho más grande y mucho más terrible que el de las mujeres maltratadas.",
    "author": "Cavernal Juan Sandoval Íñiguez",
    "info_author": "",
    "comment": "Es más, si la mujer maltratada practica la resignación, casi ni crimen es."
  },
  { "points": 0,
    "region": "",
    "hashtags": [],
    "date": "03/2021",
    "text": "Otra razón, y de mucho peso, es querer enfrentar a los hombres y a las mujeres. Que se odien, que se aborrezcan. [...] Allí está la dialéctica del marxismo. Hegel la pensó en las ideas, pero Marx la trajo a la práctica. Enfrentar a los opuestos para borrar las diferencias según eso. Enfrentar al trabajador con el patrón, al blanco con el indio, al hombre con la naturaleza. Y ahora, al varón con la mujer. Hacer a los hombres odiosos. Eso es dañoso para una sociedad...",
    "author": "Cavernal Juan Sandoval Íñiguez",
    "info_author": ", sobre su oposición al feminismo.",
    "comment": "Hegel, feminismo, dialéctica. ¿Quién dijo que la Iglesia no tiene filósofos?"
  },
  { 
    "points": 0,
    "region": "",
    "hashtags": ["HazañasDeLaInfrencia"],
    "date": "",
    "text": "Los extranjeros que nos atacan son de otro país.",
    "author": "Nicolás Maduro",
    "info_author": "",
    "comment": "No se burlen. Es un discurso sobre Kant y los juicios sintéticos a priori, ¿ah verdad?"
  },
  {
    "points": 0,
    "region": "",
    "hashtags": ["HazañasDeLaInfrencia"],
    "date": "",
    "text": "Demasiada coincidencia que maten a alguien y al día siguiente esté muerto.",
    "author": "Nicolás Maduro",
    "info_author": "",
    "comment": "¡Qué tiempos! Se está muriendo mucha gente que antes no se moría."
  }
]

//const object = JSON.stringify(general_list)


/*
Nuevo objeto: 
{
 "points": 0,
 "region": "",
 "hashtags": [],
 "date": "",
 "text": "",
 "author": "",
 "info_author": "",
 "comment": ""
},

*/

